services:
  mkdocs-dev:
    container_name: mkdocs-dev
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/docs:rw
    platform: linux/amd64

  # mkdocs:
  #   container_name: mkdocs
  #   build: .
  #   ports:
  #     - 8001:80
  #   volumes:
  #     - ./:/docs:rw
  #   tty: true
  #   stdin_open: true
  #   platform: linux/amd64
