services:
  mkdocs-test:
    container_name: mkdocs-test
    # image: javanile/mkdocs:latest
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app:ro
    # command: ["mkdocs", "serve"]
